# Generated by Django 2.1.5 on 2019-04-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.png', upload_to='E:/images/'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='tittle',
            field=models.CharField(default='作品标题', max_length=100),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.CharField(default='在这里输入作品的简介', max_length=100),
        ),
    ]
