# Generated by Django 2.1.5 on 2019-04-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190421_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
