# Generated by Django 2.1.5 on 2019-04-23 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField()),
                ('image', models.ImageField(default='default.png', upload_to='images/')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('last_updated_time', models.DateTimeField(auto_now=True, verbose_name='更新日期')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
    ]
